config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
root 'products#index'
resources :products, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock_checker.rb
module StockChecker
  def self.check_stock(product)
    shopify_inventory_data = ShopifyService.get_inventory_level(product['products_model'])

    if shopify_inventory_data[:status] == "200"
      shopify_inventory = shopify_inventory_data[:quantity].to_i

      if shopify_inventory > 0
        return 'In Stock'
      elsif shopify_inventory == 0 && product['in_stock_qty'].to_i > 0
        return '4 - 6 Weeks ETA'
      else
        return 'Out of Stock'
      end
    else
      return "API Error: #{shopify_inventory_data[:status]} - #{shopify_inventory_data[:error]}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'faraday'
  require 'json'

def index
offset = params[:offset].to_i + 1 # Increment the offset by 1

  conn = Faraday.new('https://www.seeedstudio.com/rest/V1/product/multiple', headers: {'Authorization': 'Bearer 2fcdf4zk3q50g0m0p0hsxlc5tfz3g4we', 'Content-Type': 'application/form-data'})

  response = conn.post do |req|
    req.params['appid'] = 'C000009484'
    req.params['limit'] = 50
    req.params['offset'] = offset
    req.params['sort'] = 'no'
  end

  @status = response.status

  begin
    products_data = JSON.parse(response.body)
    @products = products_data['data']

    # Filter products based on search query
    search_query = params[:search]
    if search_query.present?
      @products = @products.select do |product|
        product['products_name'].to_s.downcase.include?(search_query.downcase) ||
          product['products_model'].to_s.downcase.include?(search_query.downcase) ||
          # Add more fields to include in the search if necessary
          # ...
          product['products_description'].to_s.downcase.include?(search_query.downcase)
      end
    end
  rescue JSON::ParserError => e
    puts "Failed to parse JSON: #{e.message}"
    @products = []
  end

  @offset = offset

  unless @products.is_a?(Array)
    puts "'data' not found in the response body or it's not an Array"
    @products = []
  end
end

def inventory_status
    shopify_api = ShopifyAPI.new
    shopify_product = shopify_api.get_product(self.sku)
    if shopify_product["inventory_quantity"] > 0
      'In Stock'
    elsif self.stock_quantity > 0
      '4 - 6 Weeks eta'
    else
      'Out of Stock'
    end
  end

  def show
    conn = Faraday.new("https://www.seeedstudio.com/rest/V1/product/multiple/skus", headers: {'Authorization': 'Bearer 2fcdf4zk3q50g0m0p0hsxlc5tfz3g4we', 'Content-Type': 'application/form-data'})
    
    response = conn.post do |req|
      req.params['appid'] = 'C000009484'
      req.params['skus'] = params[:id]
    end

    @product = JSON.parse(response.body)['data'].first
    @status = response.status
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopify_helper.rb
module ShopifyHelper
  def fetch_shopify_inventory(product)
    variant_id = product.shopify_variant_id
    shopify_product = ShopifyAPI::Variant.find(variant_id, params: { fields: 'inventory_quantity' })
    shopify_product.inventory_quantity
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeeedStockSync</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

      <!-- Add Bootstrap CSS via CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Add Bootstrap JavaScript and its dependencies (jQuery and Popper.js) via CDN, if needed -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <h1>Shopify api version</h1>
  <p>Status: <%= @status %></p>

  <!-- Search Form -->
  <form action="<%= products_path %>" method="GET">
    <div class="form-group">
      <input type="text" name="search" class="form-control" placeholder="Search..." />
    </div>
    <div class="form-group">
      <input type="submit" value="Search" class="btn btn-primary" />
      <input type="button" value="Reset" onclick="window.location.href='<%= products_path %>'" class="btn btn-secondary" />
    </div>
  </form>

<div class="text-right">
    <%= link_to 'Previous', products_path(offset: @offset - 2), class: 'btn btn-primary' if @offset > 0 %>
    <%= link_to 'Next', products_path(offset: @offset.to_i + 0), class: 'btn btn-primary' %>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Product Name</th>
          <th>SKU</th>
          <th>Link</th>
          <th>Seeed Price</th>
          <th>EUCA Price</th>
          <th>ROI (21.50)</th>
          <th>Seeed Stock</th>
          <th>Stock</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product['entity_id'] %></td>
            <td><%= product['products_name'] %></td>
            <td><%= product['products_model'] %></td>
            <td><%= link_to product['products_name'], product['page_link'], target: "_blank" %></td>
            <td><%= number_to_currency(product['products_price'], unit: "$", precision: 2) %></td>
            <td><%= number_to_currency(product['products_price'].to_f * 1.10, unit: "$", precision: 2) %></td>
            <td><%= number_to_currency((product['products_price'].to_f * 1.10) * 21.5, unit: "R", precision: 2) %></td>
            <td style="color: <%= product['in_stock_qty'].to_i.zero? ? 'red' : 'green' %>;">
              <%= product['in_stock_qty'] %>
            </td>
            <td><%= StockChecker.check_stock(product) %></td> 
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<div class="text-center">
     <%= link_to 'Previous', products_path(offset: @offset - 2), class: 'btn btn-primary' if @offset > 0 %>
    <%= link_to 'Next', products_path(offset: @offset.to_i + 0), class: 'btn btn-primary' %>
  </div>


</div>

app/views/products/show.html.erb
<h1><%= @product['products_name'] %></h1>
<p>Status: <%= @status %></p>

<!-- Display all the other details as required -->
<p><%= @product['products_model'] %></p>
<!-- add more fields as necessary -->